CREATE DATABASE RESTAURANTE
GO 
USE RESTAURANTE
GO
CREATE TABLE CARTA (
IDPLATO INT PRIMARY KEY IDENTITY (1,1) ,
NOMBRE VARCHAR (50) ,
PRECIO MONEY ,
TIPO VARCHAR (50),
TENEDOR BIT ,
CUCHILLO BIT ,
CUCHARA BIT 
)

INSERT INTO CARTA (NOMBRE,PRECIO,TIPO,TENEDOR,CUCHILLO,CUCHARA)
VALUES 
('FLAN',110,'POSTRE',0,0,1),
('TARTA', 120,'PRINCIPAL',1,1,0),
('ENSALADA DE RUCULA',150,'ENTRADA',1,1,0)

CREATE TABLE VAJILLA (
ID INT PRIMARY KEY IDENTITY (1,1),
NOMBRE VARCHAR (50) ,
CANTIDAD INT ,
PRECIO MONEY ,
TIPO VARCHAR (50)
)
INSERT INTO VAJILLA (NOMBRE,CANTIDAD,PRECIO,TIPO)
VALUES 
('TENEDOR',80,40,'Vajilla'),
('COPA',60,20,'Vajilla'),
('VASOS',100,50,'Vajilla'),
('CUCHILLO',80,55,'Vajilla')
