CREATE DATABASE Barzola
GO 
USE [Barzola]
GO
/****** Object:  Table [dbo].[PLATO]    Script Date: 25/05/2019 1:07:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PLATO](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [varchar](50) NOT NULL,
	[DESCRIPCION] [varchar](50) NULL,
	[TIPO] [bigint] NOT NULL,
	[PRECIO] [money] NOT NULL,
	[ESTADO] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC,
	[NOMBRE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TIPO_PLATO]    Script Date: 25/05/2019 1:07:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TIPO_PLATO](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [varchar](50) NOT NULL,
	[estado] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  View [dbo].[view_platos]    Script Date: 25/05/2019 1:07:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE view [dbo].[view_platos]
as select p.id,p.NOMBRE,p.PRECIO,p.TIPO as idtipo,tp.NOMBRE as Tipo,p.ESTADO,p.DESCRIPCION from PLATO as p
inner join TIPO_PLATO as tp on tp.ID=p.TIPO
GO
/****** Object:  Table [dbo].[VAJILLAXPLATO]    Script Date: 25/05/2019 1:07:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VAJILLAXPLATO](
	[IDVAJILLA] [int] NOT NULL,
	[IDPLATO] [bigint] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[IDVAJILLA] ASC,
	[IDPLATO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[VAJILLA]    Script Date: 25/05/2019 1:07:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VAJILLA](
	[ID] [int] IDENTITY(10,1) NOT NULL,
	[NOMBRE] [varchar](50) NOT NULL,
	[CANTIDAD] [int] NULL,
	[ESTADO] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[NOMBRE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  View [dbo].[view_vajillaXplato]    Script Date: 25/05/2019 1:07:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create view [dbo].[view_vajillaXplato]
as select vp.IDPLATO,v.NOMBRE  from VAJILLAXPLATO as vp
inner join VAJILLA as v on v.ID=vp.IDVAJILLA
GO
/****** Object:  View [dbo].[View_VajillaXPla]    Script Date: 25/05/2019 1:07:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE view [dbo].[View_VajillaXPla]
as select  p.NOMBRE as nombrePla,v.NOMBRE as nombrevaj, p.ID as idpla,v.ID as idvaj from vajillaxplato as vp
inner join VAJILLA as v on vp.IDVAJILLA=v.ID
inner join PLATO as p on p.ID=vp.IDPLATO
GO
/****** Object:  Table [dbo].[BEBIDA]    Script Date: 25/05/2019 1:07:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BEBIDA](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[IDMARCA] [bigint] NOT NULL,
	[NOMBRE] [varchar](50) NOT NULL,
	[DESCRIPCION] [varchar](50) NULL,
	[PRECIO] [money] NOT NULL,
	[COPA] [bit] NOT NULL,
	[CANTIDAD] [int] NULL,
	[ESTADO] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC,
	[IDMARCA] ASC,
	[NOMBRE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MARCA]    Script Date: 25/05/2019 1:07:26 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MARCA](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [varchar](50) NOT NULL,
	[ESTADO] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC,
	[NOMBRE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  View [dbo].[View_marca]    Script Date: 25/05/2019 1:07:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE view [dbo].[View_marca]
as select b.NOMBRE as nombre_bebida, b.PRECIO,
b.ID, b.ESTADO,b.DESCRIPCION,b.COPA,b.CANTIDAD,m.NOMBRE as marca, m.ID as marcaid from BEBIDA as b
inner join MARCA as M on m.ID=b.IDMARCA
GO
/****** Object:  Table [dbo].[BEBIDASXPEDIDO]    Script Date: 25/05/2019 1:07:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BEBIDASXPEDIDO](
	[IDPEDIDO] [bigint] NOT NULL,
	[IDBEBIDA] [bigint] NOT NULL,
	[CANTIDAD] [bigint] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[IDPEDIDO] ASC,
	[IDBEBIDA] ASC,
	[CANTIDAD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[EMPLEADO]    Script Date: 25/05/2019 1:07:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EMPLEADO](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [varchar](50) NOT NULL,
	[APELLIDO] [varchar](50) NOT NULL,
	[IDPUESTO] [bigint] NOT NULL,
	[ESTADO] [bit] NOT NULL,
	[USUARIO] [varchar](50) NOT NULL,
	[CONTRASENA] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MESA]    Script Date: 25/05/2019 1:07:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MESA](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[IDMESERO] [bigint] NOT NULL,
	[ESTADO] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PEDIDOS]    Script Date: 25/05/2019 1:07:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PEDIDOS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[IDMESA] [bigint] NOT NULL,
	[ESTADO] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PLATOSXPED]    Script Date: 25/05/2019 1:07:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PLATOSXPED](
	[IDPEDIDO] [bigint] NOT NULL,
	[IDPLATO] [bigint] NOT NULL,
	[CANTIDAD] [bigint] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[IDPEDIDO] ASC,
	[IDPLATO] ASC,
	[CANTIDAD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PUESTO]    Script Date: 25/05/2019 1:07:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PUESTO](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TIPO_PLATO] ADD  DEFAULT ('') FOR [estado]
GO
ALTER TABLE [dbo].[BEBIDA]  WITH CHECK ADD  CONSTRAINT [FK_BEBIDA] FOREIGN KEY([IDMARCA])
REFERENCES [dbo].[MARCA] ([ID])
GO
ALTER TABLE [dbo].[BEBIDA] CHECK CONSTRAINT [FK_BEBIDA]
GO
ALTER TABLE [dbo].[BEBIDASXPEDIDO]  WITH CHECK ADD  CONSTRAINT [FK_BEBIDASXPE] FOREIGN KEY([IDPEDIDO])
REFERENCES [dbo].[PEDIDOS] ([ID])
GO
ALTER TABLE [dbo].[BEBIDASXPEDIDO] CHECK CONSTRAINT [FK_BEBIDASXPE]
GO
ALTER TABLE [dbo].[BEBIDASXPEDIDO]  WITH CHECK ADD  CONSTRAINT [FK_BEBIDASXPEDOS] FOREIGN KEY([IDBEBIDA])
REFERENCES [dbo].[BEBIDA] ([ID])
GO
ALTER TABLE [dbo].[BEBIDASXPEDIDO] CHECK CONSTRAINT [FK_BEBIDASXPEDOS]
GO
ALTER TABLE [dbo].[EMPLEADO]  WITH CHECK ADD  CONSTRAINT [FK_IDPUESTO] FOREIGN KEY([IDPUESTO])
REFERENCES [dbo].[PUESTO] ([ID])
GO
ALTER TABLE [dbo].[EMPLEADO] CHECK CONSTRAINT [FK_IDPUESTO]
GO
ALTER TABLE [dbo].[MESA]  WITH CHECK ADD  CONSTRAINT [FK_IDMESERO] FOREIGN KEY([IDMESERO])
REFERENCES [dbo].[EMPLEADO] ([ID])
GO
ALTER TABLE [dbo].[MESA] CHECK CONSTRAINT [FK_IDMESERO]
GO
ALTER TABLE [dbo].[PEDIDOS]  WITH CHECK ADD  CONSTRAINT [FK_IDMESA] FOREIGN KEY([IDMESA])
REFERENCES [dbo].[MESA] ([ID])
GO
ALTER TABLE [dbo].[PEDIDOS] CHECK CONSTRAINT [FK_IDMESA]
GO
ALTER TABLE [dbo].[PLATO]  WITH CHECK ADD  CONSTRAINT [FK_PLATO] FOREIGN KEY([TIPO])
REFERENCES [dbo].[TIPO_PLATO] ([ID])
GO
ALTER TABLE [dbo].[PLATO] CHECK CONSTRAINT [FK_PLATO]
GO
ALTER TABLE [dbo].[PLATOSXPED]  WITH CHECK ADD  CONSTRAINT [FK_PLATOXPED] FOREIGN KEY([IDPLATO])
REFERENCES [dbo].[PLATO] ([ID])
GO
ALTER TABLE [dbo].[PLATOSXPED] CHECK CONSTRAINT [FK_PLATOXPED]
GO
ALTER TABLE [dbo].[PLATOSXPED]  WITH CHECK ADD  CONSTRAINT [FK_PLAXPE] FOREIGN KEY([IDPEDIDO])
REFERENCES [dbo].[PEDIDOS] ([ID])
GO
ALTER TABLE [dbo].[PLATOSXPED] CHECK CONSTRAINT [FK_PLAXPE]
GO
ALTER TABLE [dbo].[VAJILLAXPLATO]  WITH CHECK ADD  CONSTRAINT [FK_VAJILLA] FOREIGN KEY([IDVAJILLA])
REFERENCES [dbo].[VAJILLA] ([ID])
GO
ALTER TABLE [dbo].[VAJILLAXPLATO] CHECK CONSTRAINT [FK_VAJILLA]
GO
ALTER TABLE [dbo].[VAJILLAXPLATO]  WITH CHECK ADD  CONSTRAINT [FK_VAXPLA] FOREIGN KEY([IDPLATO])
REFERENCES [dbo].[PLATO] ([ID])
GO
ALTER TABLE [dbo].[VAJILLAXPLATO] CHECK CONSTRAINT [FK_VAXPLA]
GO

select *from View_VajillaXPla