CREATE DATABASE Barzola
GO 
USE BARZOLA
GO
CREATE TABLE PEDIDOS (
ID BIGINT NOT NULL IDENTITY (1,1),
IDMESA BIGINT NOT NULL ,
ESTADO BIT NOT NULL,
PRIMARY KEY (ID)
)
GO
CREATE TABLE MESA (
ID BIGINT NOT NULL IDENTITY (1,1), 
IDMESERO BIGINT NOT NULL,
ESTADO BIT NOT NULL,
PRIMARY KEY (ID)
)
GO
CREATE TABLE EMPLEADO (
ID BIGINT PRIMARY KEY IDENTITY (1,1),
NOMBRE VARCHAR (50) NOT NULL,
APELLIDO VARCHAR (50)NOT NULL,
IDPUESTO BIGINT NOT NULL,
ESTADO BIT NOT NULL,
USUARIO VARCHAR (50) NOT NULL ,
CONTRASENA VARCHAR (50) NOT NULL 
)
GO 
CREATE TABLE PUESTO(
ID BIGINT NOT NULL PRIMARY KEY IDENTITY (1,1),
NOMBRE VARCHAR (50) NOT NULL
)
GO
ALTER TABLE PEDIDOS 
ADD CONSTRAINT FK_IDMESA FOREIGN KEY (IDMESA) REFERENCES MESA (ID)
GO
ALTER TABLE MESA
ADD CONSTRAINT FK_IDMESERO FOREIGN KEY (IDMESERO) REFERENCES EMPLEADO (ID)
GO
ALTER TABLE EMPLEADO
ADD CONSTRAINT FK_IDPUESTO FOREIGN KEY (IDPUESTO)REFERENCES PUESTO (ID) 

CREATE TABLE BEBIDASXPEDIDO(
IDPEDIDO  BIGINT NOT NULL,
IDBEBIDA BIGINT NOT NULL,
CANTIDAD BIGINT NOT NULL,
PRIMARY KEY (IDPEDIDO,IDBEBIDA,CANTIDAD)
)
GO
CREATE TABLE BEBIDA (
ID BIGINT IDENTITY (1,1) UNIQUE ,
IDMARCA BIGINT NOT NULL ,
NOMBRE VARCHAR (50) NOT NULL ,
DESCRIPCION VARCHAR (50),
PRECIO MONEY NOT NULL, 
COPA BIT NOT NULL,
CANTIDAD INT,
ESTADO BIT NOT NULL
PRIMARY KEY (ID,IDMARCA,NOMBRE)
) 
CREATE TABLE MARCA (
ID BIGINT  IDENTITY (1,1) NOT NULL UNIQUE ,
NOMBRE VARCHAR (50) NOT NULL,
ESTADO BIT NOT NULL
PRIMARY KEY (ID, NOMBRE)
)
GO

ALTER TABLE BEBIDASXPEDIDO
ADD CONSTRAINT FK_BEBIDASXPE FOREIGN KEY (IDPEDIDO) REFERENCES PEDIDOS (ID)
GO
ALTER TABLE BEBIDASXPEDIDO
ADD CONSTRAINT FK_BEBIDASXPEDOS FOREIGN KEY (IDBEBIDA) REFERENCES BEBIDA (ID)

ALTER TABLE BEBIDA 
ADD CONSTRAINT FK_BEBIDA FOREIGN KEY (IDMARCA) REFERENCES MARCA(ID)

CREATE TABLE PLATOSXPED(
IDPEDIDO BIGINT NOT NULL ,
IDPLATO BIGINT NOT NULL ,
CANTIDAD BIGINT NOT NULL
PRIMARY KEY (IDPEDIDO,IDPLATO,CANTIDAD)
)

CREATE TABLE PLATO (
ID BIGINT  IDENTITY (1,1) UNIQUE ,
NOMBRE VARCHAR (50) NOT NULL ,
DESCRIPCION VARCHAR (50),
TIPO BIGINT NOT NULL ,
PRECIO MONEY NOT NULL 
PRIMARY KEY(ID,NOMBRE),
ESTADO BIT NOT NULL

)
CREATE TABLE TIPO_PLATO (
ID BIGINT NOT NULL PRIMARY KEY IDENTITY (1,1),
NOMBRE VARCHAR (50) NOT NULL
)

CREATE TABLE VAJILLAXPLATO (
IDVAJILLA INT NOT NULL ,
IDPLATO bigINT NOT NULL 
PRIMARY KEY(IDVAJILLA,IDPLATO)
)
CREATE TABLE VAJILLA (
ID INT NOT NULL IDENTITY (10,1)PRIMARY KEY, 
NOMBRE VARCHAR (50) NOT NULL UNIQUE ,
CANTIDAD INT ,
ESTADO BIT NOT NULL
)
ALTER TABLE PLATO
ADD CONSTRAINT FK_PLATO FOREIGN KEY (TIPO) REFERENCES TIPO_PLATO (ID)

ALTER TABLE PLATOSXPED
ADD CONSTRAINT FK_PLAXPE FOREIGN KEY (IDPEDIDO) REFERENCES PEDIDOS (ID)

ALTER TABLE PLATOSXPED
ADD CONSTRAINT FK_PLATOXPED FOREIGN KEY (IDPLATO) REFERENCES PLATO (ID)

ALTER TABLE VAJILLAXPLATO 
ADD CONSTRAINT FK_VAXPLA FOREIGN KEY (IDPLATO) REFERENCES PLATO (ID)

ALTER TABLE VAJILLAXPLATO
ADD CONSTRAINT FK_VAJILLA FOREIGN KEY (IDVAJILLA) REFERENCES VAJILLA (ID)

INSERT INTO MARCA(NOMBRE,ESTADO)
VALUES 
('VILLA DEL SUR',1),
('PEPSI',1),
('COCA COLA',0)

INSERT INTO BEBIDA (IDMARCA,NOMBRE,DESCRIPCION,PRECIO,COPA, ESTADO)
VALUES 
(1,'AGUA SABORIZADA','BOTELLA DE 600ML',60,0,1),
(2,'GASEOSA LIMA','LATA DE 250ML',40,0,1),
(3,'GASEOSA NARANJA','BOTELLA DE 600ML',65,0,1)


INSERT INTO TIPO_PLATO (NOMBRE)
VALUES 
('POSTRE'),
('PLATO PRINCIPAL'),
('ENTRADA'), 
('GUARNICION')

INSERT  INTO PLATO (NOMBRE,DESCRIPCION,TIPO,PRECIO,ESTADO)
VALUES 
('PANQUEQUES','PACOMPANADOS CON DULCE',1,50,1),
('FLAN','CON DULCE DE LECHE O CREMA',1,110,1),
('PIZZA DE MUZZA','MUZZARELLA',2,280,1),
('DORITOS CON CHEDAR',NULL,3,90,1)

INSERT  INTO VAJILLA (NOMBRE,CANTIDAD,ESTADO)
VALUES
('CUCHILLO',21,1),
('CUCHARA',1,1),
('TENEDOR',4,1)
select  V.ID,V.NOMBRE, V.CANTIDAD From VAJILLA as V

insert into vajilla (nombre,cantidad,ESTADO) values ('Palos chinos',3,1)

INSERT  INTO VAJILLAXPLATO (IDVAJILLA,IDPLATO)
VALUES
(10,1),
(11,1),
(12,2)
SELECT *FROM VAJILLA

CREATE view View_marca
as select b.NOMBRE as nombre_bebida, b.PRECIO,
b.ID, b.ESTADO,b.DESCRIPCION,b.COPA,b.CANTIDAD,m.NOMBRE as marca, m.ID as marcaid from BEBIDA as b
inner join MARCA as M on m.ID=b.IDMARCA