CREATE DATABASE RESTAURANTE
GO 
USE RESTAURANTE
GO
CREATE TABLE CARTA (
IDPLATO INT PRIMARY KEY IDENTITY (1,1),
NOMBRE VARCHAR (50) NOT NULL,
PRECIO MONEY NOT NULL,
TIPO VARCHAR (50),
TENEDOR BIT NOT NULL,
CUCHILLO BIT NOT NULL,
CUCHARA BIT NOT NULL
)
